name: CI Pipeline for Containerized Applications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t my-container:latest .

    - name: Run unit tests
      run: |
        docker run --rm my-container:latest /bin/sh -c "run-tests.sh"

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg
        curl -fsSL https://aquasec.com/repo.gpg | gpg --dearmor -o /usr/share/keyrings/aquasec-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/aquasec-archive-keyring.gpg] https://aquasec.com/repo/deb/ stable main" | sudo tee /etc/apt/sources.list.d/aquasec.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: Run Trivy Scan
      run: trivy image my-container:latest

    - name: Upload Trivy Scan Report
      uses: actions/upload-artifact@v3  # Updated to the latest version
      with:
        name: trivy-report
        path: trivy-report.html
